### ISSUE TITLE
PS4 buttons addon link does not work

### ISSUE THREAD

**Issue by ddubs13** [quinton-ashley/Super_Mario_Sunshine_UHD_Texture_Pack#10]
A previous issue highlighting this was shot down. The author claims the link still works, but I just checked today and it does not work, it simply says "Not Found".

![image](https://user-images.githubusercontent.com/49102220/142733030-faac7913-783d-4f4c-9594-ef036ccb2737.png)

I have tried both simply clicking and right clicking and saving. When I do the latter, it says "Failed - No File". I don't know why the author has no issue with this, but other people like myself (and presumably the person before) do.

**Comment by quinton-ashley** [comment]
ah I see the problem. I fixed it for you. Here is the link
https://github.com/quinton-ashley/Super_Mario_Sunshine_UHD_Texture_Pack/releases/download/2.1.1/SMS_PS4_Button_Textures.zip

**Comment by ddubs13** [comment]
> ah I see the problem. I fixed it for you. Here is the link https://github.com/quinton-ashley/Super_Mario_Sunshine_UHD_Texture_Pack/releases/download/2.1.1/SMS_PS4_Button_Textures.zip

Might want to add that link to the main github page.

**Comment by quinton-ashley** [comment]
yup haha whoops, just added it
