### ISSUE TITLE
PS4 Button Textures

### ISSUE THREAD

**Issue by Tokobotenkai** [quinton-ashley/Super_Mario_Sunshine_UHD_Texture_Pack#11]
I just wanted to say I just found this project today and you're doing an awesome job!

Just wanted to clarify on how to thse the PS4 Button Textures, I replaced the files in the texture folders but I still see the B button prompts and stuff.

Anything I am doing wrong?

**Comment by quinton-ashley** [comment]
Thank you!!

Are you playing the North American version of the game? I only see one font file for the ps4 textures and idk which one it is for actually. Never used these ps4 textures myself so I couldn't tell ya.

**Comment by Tokobotenkai** [comment]
I am using NTSC-U but not sure if it is the NA edition (code is GMSE01).

I did some test runs and even installing Dolphin on an M1 Max Macbook Pro (it works).

I installed the Snap package of the developmental version of Dolphin and the custom textures doesn't seem to load (not sure the directory paths are the same for Snap).

Any idea how do I workaround that? 

Currently, I have been trying to compile Dolphin myself with no success. Seems like the installer is broken for now. The Ubuntu PPA repo has no focal (20.04) release either.

**Comment by Tokobotenkai** [comment]
Okay, I can confirm it works, found where snap config files are at. I mapped my keys in about the same layout as the Gamecube controller, which now my Circle button is shown as the square button. A minor issue but I guess it works!

The other parts of the game show B button prompts, so I guess I will skip the PS4 button prompts.

Thanks again for your amazing work.

**Comment by DAOWAce** [comment]
> The other parts of the game show B button prompts, so I guess I will skip the PS4 button prompts.

So it's incomplete?

Had been wondering why I couldn't get this to work..  only tested it at the start of the game.
