### ISSUE TITLE
Game fails to load

### ISSUE THREAD

**Issue by ConnorRK** [quinton-ashley/Super_Mario_Sunshine_UHD_Texture_Pack#2]
This file causes the game to hang up. When deleted everything else loads in properly.
"Super_Mario_Sunshine_UHD_Texture_Pack/GMS/environment/pollution_maps/tex1_512x512_78e99302b44e7fa1_1.png "

**Comment by quinton-ashley** [comment]
I don't have any problem with that texture on the latest version of dolphin 8633.  What version are you using?

**Comment by ConnorRK** [comment]
I'm running the stable 5.0 release. That appears to be the first and only file to attempt to load. I am able to delete/move every other image but that one says it's being used by dolphin. Once the offending image is removed the other files can be loaded and the game loads correctly.

**Comment by quinton-ashley** [comment]
This pack uses DDS BC7 textures and is only fully compatible with the latest version of Dolphin.
