### ISSUE TITLE
Latest release is misformatted

### ISSUE THREAD

**Issue by Tank-Missile** [quinton-ashley/Super_Mario_Sunshine_UHD_Texture_Pack#4]
The Resource Pack Manager does not recognize .7z archives, and the top level directory of the archive needs to be the textures, logo, and manifest. Dolphin Emulator will crash due to the archive being misformatted, though I suspect the crash is a bug in the emulator itself. Just to be clear, the crash was caused by simply unzipping and rezipping the archive as a .zip archive without fixing the directory structure.

**Comment by quinton-ashley** [comment]
Hopefully Dolphin will support 7z in the future and not crash.  You should submit a feature request to the Dolphin developers.  I'm sorry but I don't have any interest in making changes to the release to accommodate the resource pack manager in it's current form.

**Comment by Tank-Missile** [comment]
Out of curiously, is there any reason why you can't just use .zip, and not use the GMS folder at the top level of the archive? I will report the crash bug I encountered though. The bug is not caused by the 7z format, but a misformatted .zip archive.

**Comment by quinton-ashley** [comment]
I think the resource pack manager needs to be improved before it can be useful for the community.  I'm not going to use an inferior compression format and make everyone's downloads longer because of this Dolphin feature's limitations.
