### ISSUE TITLE
Lower part of “Ç” (capital cedilla) visible above “à”

### ISSUE THREAD

**Issue by Scall** [quinton-ashley/Super_Mario_Sunshine_UHD_Texture_Pack#5]
As you can see in this screenshot (game language set to **Italian**):
https://www.dropbox.com/s/ku1f21if1zqd8ar/Super_Mario_Sunshine_UHD_Texture_Pack-%C3%A0-issue.png

Steps to reproduce the issue:
1. Start the **European** version of the game.
2. Set the **Italian** or **French** language in the options, if the current language is different.
3. Talk with any NPC with the letter “**à**” (a with grave accent) in their dialogue.

Possible solution: in `textures/GMS/gui/fonts/tex1_512x256_3805b95c880e2ed2_0.png` have the capital cedilla slightly raised, or with its hook slightly cropped.

Note: the cedilla is not used in Italian, but both the cedilla and “**à**” are used in French. However, in the game, NPCs such as Piantas say “Ca” instead of “Ça”; don't know if it is spelled correctly in other dialogues (just to say there is a possibility that the capital cedilla is not even used).

**Comment by quinton-ashley** [comment]
Should be an easy enough fix to do yourself. Send me the edited image and I will add it.

**Comment by Scall** [comment]
Here it is:
https://www.dropbox.com/s/8zpd6c2pe51omk8/tex1_512x256_3805b95c880e2ed2_0.png?dl=1

**Comment by quinton-ashley** [comment]
Thanks for your contribution to the texture pack! It's been included in v2.1.0 :)
