### ISSUE TITLE
hi i fixed this for you :)

### ISSUE THREAD

**Issue by cheatfreak47** [quinton-ashley/Super_Mario_Sunshine_UHD_Texture_Pack#7]
![17651180667255390208_20201004075208_1](https://user-images.githubusercontent.com/7818664/95014774-2635b300-0617-11eb-8634-4f2d20f0ad19.png)

[misc.zip](https://github.com/quinton-ashley/Super_Mario_Sunshine_UHD_Texture_Pack/files/5323150/misc.zip)

I just used the shine texture you drew in /icons/ that is half of a shine sprite, and I figured the rest out on my own. 
Feel free to use this in a texture pack update, with love, CF

**Comment by cheatfreak47** [comment]
![17651180667255390208_20201004082354_1](https://user-images.githubusercontent.com/7818664/95015459-099b7a00-061b-11eb-8a42-eb9ff0091804.png)
![17651180667255390208_20201004081721_1](https://user-images.githubusercontent.com/7818664/95015462-0acca700-061b-11eb-8fa0-5ced6c17efb4.png)
Additional images

**Comment by cheatfreak47** [comment]
misc belongs in /gui/ as it replaces some textures you already did there I think
if you leave it where it is, you'll have to delete the old ones from the old location

**Comment by quinton-ashley** [comment]
Thanks for your contribution to the texture pack! It's been included in v2.1.1 :)
