### ISSUE TITLE
higher quality M paintings

### ISSUE THREAD

**Issue by cheatfreak47** [quinton-ashley/Super_Mario_Sunshine_UHD_Texture_Pack#8]
I spent a considerable amount of effort with this to get this working. I more or less ported the higher quality video used for the M paintings in the Super Mario 3D-All Stars port as a Dolphin Texture Pack. Up to you whether or not you should add it to the pack or not.
![17651180667255390208_20201004021102_1](https://user-images.githubusercontent.com/7818664/95015727-9266e580-061c-11eb-9eb7-6fbb449453c1.png)
![17651180667255390208_20201004031756_1](https://user-images.githubusercontent.com/7818664/95015728-93981280-061c-11eb-8c37-a1e92bfa5631.png)
![17651180667255390208_20201004083552_1](https://user-images.githubusercontent.com/7818664/95015734-a27ec500-061c-11eb-83ff-3dd7fb0bc955.png)

gif video: https://gfycat.com/KindheartedOddballHornedtoad
download: https://files.catbox.moe/gij5g2.7z

**Comment by cheatfreak47** [comment]
youtube video
https://www.youtube.com/watch?v=LSG4xsyqMVQ

**Comment by quinton-ashley** [comment]
awesome! I will release an update with these today!

**Comment by quinton-ashley** [comment]
Thanks for your contribution to the texture pack! It's been included in v2.1.1 :)
