### ISSUE TITLE
PS4 button textures add-on download link broken

### ISSUE THREAD

**Issue by labmux** [quinton-ashley/Super_Mario_Sunshine_UHD_Texture_Pack#9]
When clicking on "PS4 button textures add-on" link, get redirected to a page with error message: "Not Found"

**Comment by ddubs13** [comment]
I'm surprised there's been no response...

**Comment by quinton-ashley** [comment]
oh sorry for not responding, I emailed the person who did them and they never responded :/ sorry maybe I should remove the link from the page now

**Comment by quinton-ashley** [comment]
wait nevermind, the link works I just checked it. I fixed it a long time ago so people could download the ps4 button textures right from github
